#!/usr/bin/python3

"""This module represents the RSA challenge."""

from sys import argv
from math import isqrt


with open(argv[1], 'r') as file:
    while line := file.readline():
        is_prime = False
        prime = 2
#        if len(line) > 19:
#            continue
        num = int(line)
        if num % prime == 0:
            print(f'{num}={num // prime}*{prime}')
            continue
#        prime += 1
        sqrt = isqrt(num)

        while prime <= sqrt:
            if (num % prime == 0):
                is_prime = False
                print(f'{num}={num // prime}*{prime}')
                break
            prime += 1
            is_prime = True
        if is_prime:
            print(f'{num}={num}*1')
# no condition => 31G
# > 15 => 34G
# > 17 => 34G
# > 20 => 29G
# isqrt and < 15 => 32G
# isqrt and < 16 => 28G
# isqrt and < 17 => 32G
# isqrt and < 18 => 35G
# isqrt and < 19 => 25G
# isqrt and < 20 => 18G
# isqrt and < 25 => 28G
# isqrt and prime+2 => 40G
# isqrt and prime+2 and < 18 => 44G
# isqrt and prime+2 and < 19 => 44G
# isqrt and prime+2 and < 20 => 42G
